name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check if version has changed
        id: check_version
        run: |
          VERSION=$(grep -oP "Version:\s*\K\d+(\.\d+)*" wcpos-web-checkout.php)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git fetch --prune --unshallow
          if git tag | grep -q "v$VERSION"; then
            echo "Version has not changed. Skipping release..."
            echo "::set-output name=release::false"
          else
            echo "Version has changed. Creating new release..."
            echo "::set-output name=release::true"
          fi

      - name: Create Release
        if: steps.check_version.outputs.release == 'true'
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Build and upload ZIP
        if: steps.check_version.outputs.release == 'true'
        run: |
          zip -r woocommerce-pos-web-checkout-gateway.zip . -x "*.git*"
          gh release upload v${{ env.VERSION }} woocommerce-pos-web-checkout-gateway.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
